### ISSUE TITLE
能自定義article的屬性

### ISSUE THREAD

**Issue by CarsonSlovoka** [CarsonSlovoka/gohugo-theme-ananke#18]
假設我們想要插入一張背景圖片，利用

```css
body:after {
  -moz-pointer-events: none;
  -webkit-pointer-events: none;
  -ms-pointer-events: none;
  pointer-events: none;
  -moz-transition: opacity 1.5s ease-in-out, visibility 1.5s;
  -webkit-transition: opacity 1.5s ease-in-out, visibility 1.5s;
  -ms-transition: opacity 1.5s ease-in-out, visibility 1.5s;
  transition: opacity 1.5s ease-in-out, visibility 1.5s;
  content: '';
  background-image: url(/images/bg/forest.jpg);  /* static/images/forest.jpg */
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: fixed;
  display: block;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  z-index: -1;
  visibility: visible;
  opacity: 1;
}
```

這類的方法，那麼因為以前已經有body_classes的屬性(在baseof.html)，所以有辦法置入

但是雖然圖片成功放入，但整個背景都會被圖片佔據，所以原始的文本區的背景顏色會不對，

才會希望也能在[article](https://github.com/CarsonSlovoka/gohugo-theme-ananke/blob/ff75bb068c6568ca29bffc24fe0dfb75e2a403ab/layouts/_default/single.html#L19)調整屬性
